Revert action.yml

diff --git a/.github/actions/run-cypress-tests/action.yml b/.github/actions/run-cypress-tests/action.yml
--- a/.github/actions/run-cypress-tests/action.yml
+++ b/.github/actions/run-cypress-tests/action.yml
@@ -42,7 +42,7 @@ runs:
         download-location: ${{ env.PLUGIN_NAME }}
     
     - name: Run Opensearch with A Single Plugin
-      uses: derek-ho/start-opensearch@v6
+      uses: opensearch-project/opensearch-build/.github/actions/start-opensearch@643b632712710159088d5f0798de7e91c1f2b8f7
       with:
         opensearch-version: ${{ env.OPENSEARCH_VERSION }}
         plugins: "file:$(pwd)/opensearch-security.zip"
@@ -52,7 +52,7 @@ runs:
 
     # OSD bootstrap
     - name: Run Dashboard with Security Dashboards Plugin
-      uses: derek-ho/setup-opensearch-dashboards@v3
+      uses: opensearch-project/opensearch-build/.github/actions/setup-opensearch-dashboards@643b632712710159088d5f0798de7e91c1f2b8f7
       with:
         plugin_name: security-dashboards-plugin
         opensearch_dashboards_yml: ${{ inputs.dashboards_config_file }}
@@ -105,11 +105,22 @@ runs:
       shell: bash
 
     - name: Run Cypress Tests with retry
-      uses: Wandalen/wretry.action@v3
-      with:
-        attempt_limit: 5
-        attempt_delay: 2000
-        command: |
-          cd OpenSearch-Dashboards/plugins/security-dashboards-plugin
-          yarn add cypress@13 --save-dev
-          eval ${{ inputs.yarn_command }} 
+      run: |
+        cd ./OpenSearch-Dashboards/plugins/security-dashboards-plugin
+        yarn add cypress@13 --save-dev
+
+        for attempt in {1..5}; do
+          echo "Running Cypress attempt ${attempt}/5."
+          if eval ${{ inputs.yarn_command }}; then
+            exit 0
+          fi
+
+          if [ "${attempt}" -eq 5 ]; then
+            echo "Cypress failed after ${attempt} attempts."
+            exit 1
+          fi
+
+          echo "Attempt ${attempt} failed. Retrying in 2s..."
+          sleep 2
+        done
+      shell: bash
